# Anchors
planning_group: &planning_group manipulator
collision_mesh_filename: &collision_mesh_filename package://reach_ros/demo/config/part.ply

optimization:
  radius: 0.2
  max_steps: 10
  step_improvement_threshold: 0.01

ik_solver:
  name: MoveItIKSolver
  distance_threshold: 0.0
  planning_group: *planning_group
  collision_mesh_filename: *collision_mesh_filename
  touch_links: []

evaluator:
  name: MultiplicativeEvaluator
  plugins:
    - name: ManipulabilityRatio
      planning_group: *planning_group
      jacobian_row_subset: [0, 1, 2]
    - name: JointPenalty
      planning_group: *planning_group

display:
  name: ROSDisplay
  collision_mesh_filename: *collision_mesh_filename
  kinematic_base_frame: base_link
  marker_scale: 0.05

target_pose_generator:
  name: PointCloudTargetPoseGenerator
  pcd_file: package://reach_ros/demo/config/part.pcd

logger:
  name: BoostProgressConsoleLogger